### ISSUE TITLE
Game 1 becomes unresponsive for a single user

### ISSUE THREAD

**Issue by Zebbeni** [Zebbeni/alien-empire#18]
Haven't been able to reproduce yet, but here's the situation:
1. Player A and others start a game
2. Everything working fine through mine placement, etc.
3. At some point, Player A tries doing a build action when it is not their turn.
4. All other players are still able to communicate, but Player A no longer receives game chat updates

Got these errors in the logs from separate instances of the error:

``` javascript
TypeError: Cannot set property 'structure' of undefined
    at applyBuildAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:286:60)
    at applyAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:104:11)
    at Object.module.exports.resolveGameAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:75:21)
    at Object.module.exports.resolveAction (/Users/andrewalbers/workspaces/alien-empire/game_server.js:36:20)
    at Socket.<anonymous> (/Users/andrewalbers/workspaces/alien-empire/app.js:80:30)
    at Socket.EventEmitter.emit (events.js:106:17)
    at Socket.onevent (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
```

``` javascript
TypeError: Cannot set property 'structure' of undefined
    at applyBuildAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:262:60)
    at applyAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:104:11)
    at Object.module.exports.resolveGameAction (/Users/andrewalbers/workspaces/alien-empire/game_actions.js:75:21)
    at Object.module.exports.resolveAction (/Users/andrewalbers/workspaces/alien-empire/game_server.js:36:20)
    at Socket.<anonymous> (/Users/andrewalbers/workspaces/alien-empire/app.js:80:30)
    at Socket.EventEmitter.emit (events.js:106:17)
    at Socket.onevent (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/socket.js:330:8)
    at Socket.onpacket (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/socket.js:290:12)
    at Client.ondecoded (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/Users/andrewalbers/workspaces/alien-empire/node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
```

**Comment by Zebbeni** [comment]
Haven't seen this for months, closing issue
